{% set name = "setuptools-rust" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: 02c16a2e155190e3eca8a9d41937a33e32d41d42d4c7ee7a81e50d9ba952e2bc

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=41
    - setuptools_scm >=3.4.3
  run:
    - python >=3.5
    - semantic_version >=2.6.0
    - setuptools >=41
    - toml >=0.9.0

test:
  imports:
    - setuptools_rust

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - nicoddemus
