{% set name = "setuptools-rust" %}
{% set version = "1.5.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8daccb14dc0eae1b6b6eb3ecef79675bd37b4065369f79c35393dd5c55652c7

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=62.4
    - wheel
  run:
    - python
    - semantic_version >=2.8.2,<3
    - setuptools >=62.4
    - typing_extensions >=3.7.4.3

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/PyO3/setuptools-rust/blob/v1.5.2/LICENSE
  summary: Setuptools rust extension plugin
  description: |
    setuptools-rust is a plugin for setuptools to build Rust Python extensions implemented with PyO3 or rust-cpython.
    Compile and distribute Python extensions written in Rust as easily as if they were written in C.
  dev_url: https://github.com/PyO3/setuptools-rust
  doc_url: https://setuptools-rust.readthedocs.io/
  doc_source_url: https://github.com/PyO3/setuptools-rust/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
  # setuptools is a run requirement
  skip-lints:
    - uses_setuptools
