{% set name = "setuptools-rust" %}
{% set version = "0.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: a5b5954909cbc5d66b914ee6763f81fa2610916041c7266105a469f504a7c4ca
  patches:
    - pr90.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=41
    - setuptools_scm >=3.4.3
  run:
    - python >=3.5
    - semantic_version >=2.6.0
    - setuptools >=41
    - toml >=0.9.0

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - nicoddemus
