{% set name = "setuptools-rust" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e05e456645d59429cb1021370aede73c0760e9360bbfdaaefb5bced530eb9d7

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=62.4
  run:
    - python
    - semantic_version >=2.8.2,<3
    - setuptools >=62.4
    - typing_extensions >=3.7.4.3

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
