{% set version = "1.4.1" %}

package:
  name: setuptools-rust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: 18ff850831f58ee21d5783825c99fad632da21e47645e9427fd7dec048029e76

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=62.4
    - setuptools_scm >=6.3.2
  run:
    - python >=3.7
    - semantic_version >=2.8.2,<3
    - setuptools >=62.4
    - typing_extensions >=3.7.4.3

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
