{% set name = "setuptools-rust" %}
{% set version = "0.10.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/PyO3/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1446d3985e4aaf4cc679fda8a48a73ac1390b627c8ae1bebe7d9e08bb3b33769

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - semantic_version >=2.6.0
    - setuptools
    - toml >=0.9.0

test:
  imports:
    - setuptools_rust

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - nicoddemus
