{% set name = "setuptools-rust" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: 958c5bf4ab6483d59dab888538121871cc5006354a42fb0fbd50acf03caad1de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=58.0
    - setuptools_scm >=6.3.2
  run:
    - python >=3.7
    - semantic_version >=2.8.2,<3
    - setuptools >=58.0
    - typing_extensions >=3.7.4.3

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
