{% set name = "setuptools-rust" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: d0c6cebd11fa9c3edf9a173d54c7b73ab4901391a7d8df5e6f73cf1bb9245a5d

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=41
    - setuptools_scm >=3.4.3
  run:
    - python >=3.5
    - semantic_version >=2.6.0
    - setuptools >=41
    - toml >=0.9.0

test:
  imports:
    - setuptools_rust

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - nicoddemus
