{% set name = "setuptools-rust" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PyO3/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f3eb4af4cdacc5c019e893e2a4e6e43d4e3b146df8c08010735de97dc5e2dacf

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python
    - setuptools >=41
    - setuptools_scm >=3.4.3
  run:
    - python
    - semantic_version >=2.6.0
    - setuptools >=41
    - toml >=0.9.0

test:
  imports:
    - setuptools_rust

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - nicoddemus
