travis:
  secure:
    BINSTAR_TOKEN: r0oWyiirnQOTB/a1sf5Ymb5ONxjH6dZxWkpdDJpgFhEx3kd/kDlSCOeeCfsebPTFgrJkZOgg5xil1umLA4SVG+dKZOmk1qO/JcfDB2Jq9xz+/Gd4X/ynaYb0IRVHNhufXWu7jz5TSq+t9M3/ct/Ug9d0/WVhUoDPAPPSC8F9/+vVJZ1zNY4N/oeCGGXSjZ1TC6YLcxYmyE97Zw0HnG+s+2J3hGQhkzke4I8APGsDoPluCCq5npFvdP2Q7Fzr5dueZHbD3koioABfP1GaRCSF1D3i2XZJErs8PNsALjG3zjXcg9m9Yju9Cb6hStYzSRrUscZJckrv1vdiyC1tsTmqDiqno+cfXtmEKqw/7xSFu1i5MwRps6tg6SLSUHUYW1eisPK98ilDZnq42wpmgVqEAGuPoJDi6h8/aLP6MjbFVqCidpDp6vO4peHKuy7g4d+x39WT1IfASIcFBzBTNwoCzJdwtmiQgYbYSyqst0IlyLdCehy+DKh046hgEsYziQTMRH7PvZGfsASFUY1jXSBBOVW3K72U1ozOPkwtfirty3bgnQVr3gUe4x0qYlie3serK3p0a4//HBUC6lT+SMU6GAAEzDPLZTLd+1XjqnntwcclR+5jcGtux5ggbiou2IempsfU2nB/E6x6LBAKlsAz/KRY8zqG2ZPh4kUiKW0Yt8k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
